### ISSUE TITLE
Can you give more examples about testing with enzyme?

### ISSUE THREAD

**Issue by aterribili** [lelandrichardson/enzyme-example-react-native#15]
https://github.com/lelandrichardson/enzyme-example-react-native/blob/master/test/MyComponent.js

Using Button (with onPress being called), TouchableHighlight, and other native components.

Thank you!

**Comment by KevKo1990** [comment]
It would be interesting as well to see how it works if I have a Component in a Component and both have a setState call... How would I handle that in Enzyme?
