### ISSUE TITLE
Babel requirements missing

### ISSUE THREAD

**Issue by DanielMSchmidt** [lelandrichardson/enzyme-example-react-native#2]
Hi there,

First of all thanks for providing an example, it's great to get an intro into testing RN Applications.
I just cloned it and ran `npm install` and `npm test`, but babel-core seemed to be missing, so I installed it and the babel plugins seemed to be missing, too. After I installed them the example worked, so I would suggest adding them to the package.json. If you like I could submit a PR for the required changes.

Have a nice day!

**Comment by jdebbink** [comment]
Seems weird that you have to install all those plugins...is there some "master" package that can be installed instead that will come along with all these things?

**Comment by DanielMSchmidt** [comment]
If this project would use a preset we could use the corresponding package and we would be done, I would in fact recommend this.

**Comment by jdebbink** [comment]
The project already included a preset, it just wasn't used. I created a pull request to use it - https://github.com/lelandrichardson/enzyme-example-react-native/pull/4
